# Generated by Django 5.1 on 2024-08-22 10:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
